version: '3'
services:
  mysql:
    image: mysql:latest
    command: --max_allowed_packet=1024M
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
  neo4j:
    image: neo4j:4.4.28
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
      - "7687:7687"
  arangodb:
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=test
    ports:
      - "8529:8529"
